version: '3.8'

services:
  naive-bayes-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount data directory for CSV files
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info"]
      interval: 30s
      timeout: 10s
      retries: 3