FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .
COPY default_cmd.sh ./default_cmd.sh
RUN chmod +x ./default_cmd.sh

CMD ["./default_cmd.sh"]